on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: |
      ( github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'teste') )
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
