name: 'Pull request main - v1'
on:
  push:
    branches:
      - main

  release:
    runs-on: ubuntu-latest
    steps:
      
      # Atualiza o arquivo "CHANGELOG.md"      
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Pega a versão do "package.json"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      # Extrai o conteudo do "CHANGELOG.md"
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      
      # Cria a nova tag release
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: false
          prerelease: false
