name: 'Pull request main - v1'
on:
  push:
    branches:
      - main

  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
