name: 'Pull request main - v1'
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3
    
      # Pega a versão do "package.json"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      # Atualiza o arquivo "CHANGELOG.md"      
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          
      # Commit changes
      - name: Commit CHANGELOG.md and package.json changes and create tag
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git add .
          git commit -m "chore: changelog ${{ steps.package-version.outputs.current-version }}"
      
      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin
      
      # Cria a nova tag release
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: |
            Conteúdo disponível no arquivo "CHANGELOG.md"
          draft: false
          prerelease: false
